// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh_FvH5uazTVvNnXgMDuDP4IgHos6pXGA',
    appId: '1:562664435227:web:9f7905a7297c3df7d712be',
    messagingSenderId: '562664435227',
    projectId: 'synergy-abaf6',
    authDomain: 'synergy-abaf6.firebaseapp.com',
    storageBucket: 'synergy-abaf6.appspot.com',
    measurementId: 'G-ZVBLRY5C98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvXCAJrLbWrt-ru61NB5yXMwqasZtUs1s',
    appId: '1:562664435227:android:7ef440fb955c73d8d712be',
    messagingSenderId: '562664435227',
    projectId: 'synergy-abaf6',
    storageBucket: 'synergy-abaf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE_47f98NfR0kHyPpzpTeMmu6Pw-22L24',
    appId: '1:562664435227:ios:7fed2c7092f9c73ad712be',
    messagingSenderId: '562664435227',
    projectId: 'synergy-abaf6',
    storageBucket: 'synergy-abaf6.appspot.com',
    iosBundleId: 'com.eos.synergy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE_47f98NfR0kHyPpzpTeMmu6Pw-22L24',
    appId: '1:562664435227:ios:6311d2a5e68950c0d712be',
    messagingSenderId: '562664435227',
    projectId: 'synergy-abaf6',
    storageBucket: 'synergy-abaf6.appspot.com',
    iosBundleId: 'com.eos.app.RunnerTests',
  );
}
