FROM nginx:latest
# RUN rm nginx/conf.d/default.conf
# RUN mkdir /etc/nginx/sites-available  
# RUN mkdir /etc/nginx/sites-enabled 
# COPY nginx/default /etc/nginx/sites-available
# COPY nginx/default /etc/nginx/sites-enabled
COPY default.conf /etc/nginx/conf.d